from openai import OpenAI
import os

# Ensure API key is loaded
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    raise ValueError("OPENAI_API_KEY not set in environment variables")

# Initialize OpenAI client
client = OpenAI(api_key=OPENAI_API_KEY)

def generate_answer(question: str, context: list, history: list = None) -> str:
    """
    Generate answer using OpenAI GPT model based on question, context, and chat history.

    Parameters:
        question (str): User's question
        context (list): List of context strings (from ingested documents)
        history (list): List of previous messages (for multi-turn chat)

    Returns:
        str: Answer generated by GPT model
    """
    if history is None:
        history = []

    # Build messages
    messages = [{"role": "system", "content": "You are a helpful assistant."}]

    # Include chat history
    for h in history:
        messages.append(h)

    # Include context and current question
    context_text = "\n".join(context) if context else "No context available."
    messages.append({
        "role": "user",
        "content": f"Context:\n{context_text}\n\nQuestion:\n{question}"
    })

    # Generate response
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=messages
    )

    # Return text content of first choice
    return response.choices[0].message.content
